// components/home/pricing.tsx
export function Pricing() {
  return (
    <section>
      <div className="container relative items-center mx-auto w-full md:px-12 lg:px-16">
        <div className="absolute -left-16 font-extrabold -top-[9.5rem] opacity-[0.05] font-heading text-[12rem]">
          Pricing
        </div>
        <div>
          <div className="overflow-hidden relative p-3 space-y-12 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:p-10 lg:space-y-0">
            <div className="p-2 rounded-xl border backdrop-blur shadow-xs dark:border-neutral-800">
              <div className="flex relative flex-col p-8 bg-gray-200 rounded-lg border dark:border-neutral-600">
                <div className="flex-1">
                  <h3 className="text-3xl font-semibold text-neutral-600 font-display">
                    Cumulus Cruiser
                  </h3>
                  <p className="flex flex-col items-center my-8 xl:flex-row xl:justify-center xl:items-baseline text-neutral-600">
                    <span className="flex items-baseline">
                      <span className="text-4xl font-extrabold tracking-tight">
                        $
                      </span>
                      <span className="text-6xl font-extrabold tracking-tight md:text-8xl lg:text-7xl xl:text-8xl">
                        0.00
                      </span>
                    </span>
                    <span className="ml-1 font-semibold lg:text-lg xl:text-xl text-md">
                      / month
                    </span>
                  </p>
                  <ul role="list" className="pt-6 mt-6 space-y-6">
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 rounded-full bg-neutral-600 min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-white"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-neutral-600">
                        Unlimited Bookmarks
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 rounded-full bg-neutral-600 min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-white"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-neutral-600">
                        Unlimited RSS Feeds
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 rounded-full bg-neutral-600 min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-white"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-left text-neutral-600">
                        Unlimited Text-to-Speech and Summarizations
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 rounded-full bg-neutral-600 min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-white"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-neutral-600">
                        Community Support
                      </span>
                    </li>
                  </ul>
                </div>
                <div className="mt-6">
                  <a
                    href="https://dev.briefkastenhq.com/?utm_source=docs&utm_medium=cta&utm_campaign=pricing"
                    target="_blank"
                    type="highlight"
                    className="block items-center py-3.5 px-10 w-full text-xl font-bold text-center text-white rounded-md border-2 transition duration-500 ease-in-out transform focus:ring-2 focus:ring-offset-2 focus:outline-none border-neutral-700 bg-neutral-700 shadow-xs font-display focus:ring-neutral-200"
                  >
                    Cloud
                  </a>
                </div>
              </div>
            </div>
            <div className="p-2 rounded-xl border backdrop-blur shadow-xs dark:border-neutral-800">
              <div className="flex relative flex-col p-8 rounded-lg border bg-neutral-700 dark:border-neutral-600">
                <div className="relative flex-1">
                  <h3 className="text-3xl font-semibold text-white font-display">
                    Silicon Sailor
                  </h3>
                  <p className="flex flex-col items-center my-8 text-white xl:flex-row xl:justify-center xl:items-baseline">
                    <span className="flex items-baseline">
                      <span className="text-4xl font-extrabold tracking-tight">
                        $
                      </span>
                      <span className="text-6xl font-extrabold tracking-tight md:text-8xl lg:text-7xl xl:text-8xl">
                        0.00
                      </span>
                    </span>
                    <span className="ml-1 font-semibold lg:text-lg xl:text-xl text-md">
                      / month
                    </span>
                  </p>
                  <ul role="list" className="pt-6 mt-6 space-y-6">
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 bg-white rounded-full">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-neutral-600"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-white">
                        Unlimited Bookmarks
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 bg-white rounded-full min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-neutral-600"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-white">
                        Unlimited RSS Feeds
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 bg-white rounded-full min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-neutral-600"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-left text-white">
                        Unlimited Text-to-Speech and Summarizations
                      </span>
                    </li>
                    <li className="flex">
                      <div className="inline-flex items-center w-6 h-6 bg-white rounded-full min-w-6">
                        <svg
                          className="flex-shrink-0 mx-auto w-4 h-4 text-neutral-600"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      </div>
                      <span className="ml-3 text-white">Community Support</span>
                    </li>
                  </ul>
                </div>
                <div className="z-50 mt-6">
                  <a
                    href="/docs/self-hosting"
                    type="highlight"
                    className="block items-center py-3.5 px-10 w-full text-xl font-bold text-center bg-white rounded-md border-2 border-white transition duration-500 ease-in-out transform focus:ring-2 focus:ring-offset-2 focus:outline-none shadow-xs font-display text-neutral-600 focus:ring-neutral-400 focus:ring-offset-neutral-700"
                  >
                    Self-host
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

// docs/components/Pricing.vue
<template>
  <section class="text-gray-600 body-font">
    <div class="container py-24 px-5 mx-auto">
      <div class="flex flex-col mb-20 w-full text-center">
        <h1 class="mb-2 text-3xl font-medium text-gray-900 sm:text-4xl title-font dark:text-zinc-100">
          Pricing
        </h1>
        <p class="mx-auto text-base leading-relaxed text-gray-400 lg:w-2/3">
          Free as in beer! Come one, come all!
        </p>
      </div>
      <div class="flex flex-col justify-around md:flex-row">
        <div class="p-4 w-full md:w-1/2 xl:w-1/2">
          <div class="flex overflow-hidden relative flex-col p-6 h-full rounded-lg border-2 border-gray-400">
            <span
              class="absolute top-0 right-0 py-1 px-3 text-xs tracking-widest text-white rounded-bl bg-slate-500">POPULAR</span>
            <h2 class="mb-1 text-sm font-medium tracking-widest title-font dark:text-zinc-400">
              STANDARD
            </h2>
            <h1
              class="flex items-center pb-4 mb-4 text-5xl leading-none text-gray-900 border-b border-gray-200 dark:border-zinc-600">
              <span class="dark:text-emerald-300/70">$0</span>
              <span class="ml-1 text-lg font-normal text-gray-500">/mo</span>
            </h1>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Bookmarks
            </p>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Tags
            </p>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Categories
            </p>
            <p class="flex items-center mb-6 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>REST API Access
            </p>
            <a class="flex items-center py-2 px-4 mt-auto w-full text-white rounded border-0 transition focus:outline-none bg-slate-500 dark:bg-emerald-300/50 hover:bg-slate-600"
              href="https://briefkastenhq.com/?utm_source=docs&utm_medium=pricing" target="_blank">
              Signup
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="ml-auto w-4 h-4" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="p-4 w-full md:w-1/2 xl:w-1/2">
          <div class="flex overflow-hidden relative flex-col p-6 h-full rounded-lg border-2 border-slate-600">
            <h2 class="mb-1 text-sm font-medium tracking-widest title-font dark:text-zinc-400">
              PRO
            </h2>
            <h1
              class="flex items-center pb-4 mb-4 text-5xl leading-none text-gray-900 border-b border-gray-200 dark:border-zinc-600">
              <span class="dark:text-emerald-300/70">$0</span>
              <span class="ml-1 text-lg font-normal text-gray-500">/mo</span>
            </h1>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Bookmarks
            </p>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Tags
            </p>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>Unlimited Categories
            </p>
            <p class="flex items-center mb-2 text-gray-600 dark:text-zinc-200">
              <span
                class="inline-flex flex-shrink-0 justify-center items-center mr-2 w-4 h-4 text-white bg-gray-400 rounded-full dark:bg-zinc-900">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                  class="w-3 h-3" viewBox="0 0 24 24">
                  <path d="M20 6L9 17l-5-5"></path>
                </svg> </span>REST API Access
            </p>
            <p class="my-4 text-xs text-gray-400">
              Theres no difference between these plans, its all free 😀
            </p>
            <a class="flex items-center py-2 px-4 mt-auto w-full text-white bg-gray-400 rounded border-0 transition hover:bg-gray-500 focus:outline-none dark:bg-emerald-300/20"
              href="https://briefkastenhq.com/?utm_source=docs&utm_medium=pricing" target="_blank">
              Signup
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="ml-auto w-4 h-4" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
